### ISSUE TITLE
nice example

### ISSUE THREAD

**Issue by mickae1** [darrenjs/openssl_examples#12]
Nice example Thanks you,

Do you know how to inject data from an another thread ?

In your example, you use the file descriptor to wait for any action from stdin . But what about action from an another thread ?

How can I wakeup the  poll function from an another thread ?

**Comment by darrenjs** [comment]
I would start by looking at `eventfd()` or `pipe()`.    The idea in both cases is the same: to get hold of a file descriptor the can be waited upon in the `poll`,  while the same/or-related (in case of `pipe`) file descriptor can be used to signal to `poll` thread that it should wake up.
